// Product Configuration - Generated by miShop Generator
// DO NOT EDIT - Regenerate using the generator CLI

const PRODUCT = {
    name: "Placeholder Product",
    description: "A great product from miShop",
    pricePerGram: 10,
    totalWeight: 28,
    image: "item.jpg",
    sizes: [
        { id: "full", name: "Full", weight: 28, multiplier: 1.0, percentage: 100 },
        { id: "half", name: "Half", weight: 14, multiplier: 0.5, percentage: 50 },
        { id: "quarter", name: "Quarter", weight: 7, multiplier: 0.25, percentage: 25 },
        { id: "eighth", name: "Eighth", weight: 3.5, multiplier: 0.125, percentage: 12.5 }
    ],
    created: "2024-01-01T00:00:00.000Z"
};

function calculateSizes(totalWeight) {
    return [
        { id: "full", name: "Full", weight: totalWeight, multiplier: 1.0, percentage: 100 },
        { id: "half", name: "Half", weight: totalWeight / 2, multiplier: 0.5, percentage: 50 },
        { id: "quarter", name: "Quarter", weight: totalWeight / 4, multiplier: 0.25, percentage: 25 },
        { id: "eighth", name: "Eighth", weight: totalWeight / 8, multiplier: 0.125, percentage: 12.5 }
    ];
}

function getPriceForSize(sizeId) {
    const size = PRODUCT.sizes.find(s => s.id === sizeId);
    if (!size) return 0;
    return PRODUCT.pricePerGram * size.weight;
}
