#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { Command } = require('commander');
const archiver = require('archiver');
const { loadConfig, obfuscateAddress, obfuscateApiKey, generateSalt } = require('./setup');

const SHOP_TEMPLATE_DIR = path.join(__dirname, 'template', 'shop');
const INBOX_TEMPLATE_DIR = path.join(__dirname, 'template', 'inbox');
const OUTPUT_DIR = path.join(__dirname, 'dist');

function ensureDir(dir) {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

function copyFileSync(src, dest) {
    if (fs.existsSync(src)) {
        fs.copyFileSync(src, dest);
        return true;
    }
    return false;
}

function calculateSizesForWeight(totalWeight) {
    return [
        { id: "full", name: "Full", weight: totalWeight, multiplier: 1.0, percentage: 100 },
        { id: "half", name: "Half", weight: totalWeight / 2, multiplier: 0.5, percentage: 50 },
        { id: "quarter", name: "Quarter", weight: totalWeight / 4, multiplier: 0.25, percentage: 25 },
        { id: "eighth", name: "Eighth", weight: totalWeight / 8, multiplier: 0.125, percentage: 12.5 }
    ];
}

function generateProductsJs(product) {
    let sizes;
    
    if (product.mode === 'units') {
        sizes = calculateSizesForWeight(product.maxUnits);
    } else {
        sizes = calculateSizesForWeight(product.weight);
    }
    
    return `// Product Configuration - Generated by miShop Generator
// DO NOT EDIT - Regenerate using the generator CLI

const PRODUCT = {
    name: "${product.name}",
    description: "${product.description}",
    mode: "${product.mode || 'weight'}",
    pricePerUnit: ${product.pricePerUnit || 0},
    pricePerGram: ${product.pricePerGram || 0},
    totalWeight: ${product.weight || 0},
    maxUnits: ${product.maxUnits || 10},
    image: "item.jpg",
    sizes: ${JSON.stringify(sizes, null, 4).replace(/\n/g, '\n    ')},
    created: "${new Date().toISOString()}"
};

function calculateSizesForWeight(totalWeight) {
    return [
        { id: "full", name: "Full", weight: totalWeight, multiplier: 1.0, percentage: 100 },
        { id: "half", name: "Half", weight: totalWeight / 2, multiplier: 0.5, percentage: 50 },
        { id: "quarter", name: "Quarter", weight: totalWeight / 4, multiplier: 0.25, percentage: 25 },
        { id: "eighth", name: "Eighth", weight: totalWeight / 8, multiplier: 0.125, percentage: 12.5 }
    ];
}

function getPriceForSize(sizeId) {
    const size = PRODUCT.sizes.find(s => s.id === sizeId);
    if (!size) return 0;
    if (PRODUCT.mode === 'units') {
        return PRODUCT.pricePerUnit * size.weight;
    }
    return PRODUCT.pricePerGram * size.weight;
}
`;
}

function generateConfigJs(config) {
    return `// Vendor Configuration - Generated by miShop Generator
// Address is obfuscated to prevent tampering

const VENDOR_CONFIG = {
    obfuscatedAddress: "${config.obfuscated}",
    salt: "${config.salt}",
    obfuscatedApiKey: "${config.obfuscatedApiKey || ''}",
    vendorPublicKey: "${config.vendorPublicKey || ''}",
    appName: "miShop",
    version: "1.0.0"
};
`;
}

function generateDappConf(product) {
    return `{
    "name": "miShop",
    "version": "1.0.0",
    "headline": "${product.name}",
    "description": "${product.description}",
    "icon": "./icon.svg",
    "category": "Shopping"
}`;
}

function generateInboxDappConf() {
    return `{
    "name": "miShopInbox",
    "version": "1.0.0",
    "headline": "Order Inbox",
    "description": "Receive and manage orders from your miShop stores",
    "icon": "./icon.svg",
    "category": "Shopping"
}`;
}

function generateInboxConfig(config) {
    return `// Vendor Configuration - Generated by miShop Generator
// This inbox is paired with your miShop stores

const INBOX_CONFIG = {
    vendorAddress: "${config.obfuscated}",
    appName: "miShopInbox",
    version: "1.0.0"
};
`;
}

async function buildShopMiniDapp(product, imagePath) {
    ensureDir(OUTPUT_DIR);
    
    const tempDir = path.join(OUTPUT_DIR, 'temp_shop_' + Date.now());
    ensureDir(tempDir);
    
    console.log('\n📦 Building Shop MiniDapp...\n');
    
    const vendorConfig = loadConfig();
    if (!vendorConfig) {
        console.error('\n❌ Error: Vendor config not found. Run "node setup.js <your-address>" first.\n');
        process.exit(1);
    }
    
    const files = fs.readdirSync(SHOP_TEMPLATE_DIR);
    
    for (const file of files) {
        const src = path.join(SHOP_TEMPLATE_DIR, file);
        const dest = path.join(tempDir, file);
        
        if (file === 'products.js') {
            fs.writeFileSync(dest, generateProductsJs(product));
            console.log(`   ✓ Generated: ${file}`);
        } else if (file === 'config.js') {
            fs.writeFileSync(dest, generateConfigJs(vendorConfig));
            console.log(`   ✓ Generated: ${file} (with obfuscated address)`);
        } else if (file === 'app.js') {
            let appContent = fs.readFileSync(src, 'utf8');
            appContent = appContent.replace('const OBFUSCATED_CMC_KEY = \'\';', `const OBFUSCATED_CMC_KEY = '${vendorConfig.obfuscatedApiKey}';`);
            appContent = appContent.replace('const CMC_KEY_SALT = \'\';', `const CMC_KEY_SALT = '${vendorConfig.salt}';`);
            fs.writeFileSync(dest, appContent);
            console.log(`   ✓ Generated: ${file} (with obfuscated API key)`);
        } else if (file === 'dapp.conf') {
            fs.writeFileSync(dest, generateDappConf(product));
            console.log(`   ✓ Generated: ${file}`);
        } else {
            copyFileSync(src, dest);
            console.log(`   ✓ Copied: ${file}`);
        }
    }
    
    if (imagePath) {
        if (fs.existsSync(imagePath)) {
            const ext = path.extname(imagePath);
            const destImage = path.join(tempDir, 'item' + ext);
            copyFileSync(imagePath, destImage);
            
            if (ext !== '.jpg') {
                let productsContent = fs.readFileSync(path.join(tempDir, 'products.js'), 'utf8');
                productsContent = productsContent.replace('item.jpg', 'item' + ext);
                fs.writeFileSync(path.join(tempDir, 'products.js'), productsContent);
            }
            
            console.log(`   ✓ Copied: item${ext}`);
        } else {
            console.warn(`   ⚠️  Warning: Image not found at ${imagePath}`);
        }
    }
    
    const zipPath = path.join(OUTPUT_DIR, `miniShop_${product.name.replace(/[^a-zA-Z0-9]/g, '_')}.mds.zip`);
    
    return new Promise((resolve, reject) => {
        const output = fs.createWriteStream(zipPath);
        const archive = archiver('zip', { zlib: { level: 9 } });
        
        output.on('close', () => {
            console.log(`\n✅ Shop MiniDapp created!`);
            console.log(`📁 Output: ${zipPath}`);
            console.log(`📊 Size: ${(archive.pointer() / 1024).toFixed(2)} KB\n`);
            
            fs.rmSync(tempDir, { recursive: true, force: true });
            resolve(zipPath);
        });
        
        archive.on('error', (err) => {
            reject(err);
        });
        
        archive.pipe(output);
        archive.directory(tempDir, false);
        archive.finalize();
    });
}

async function buildInboxMiniDapp() {
    ensureDir(OUTPUT_DIR);
    
    const tempDir = path.join(OUTPUT_DIR, 'temp_inbox_' + Date.now());
    ensureDir(tempDir);
    
    console.log('\n📬 Building Inbox MiniDapp...\n');
    
    const vendorConfig = loadConfig();
    if (!vendorConfig) {
        console.error('\n❌ Error: Vendor config not found. Run "node setup.js <your-address>" first.\n');
        process.exit(1);
    }
    
    const files = fs.readdirSync(INBOX_TEMPLATE_DIR);
    
    for (const file of files) {
        const src = path.join(INBOX_TEMPLATE_DIR, file);
        const dest = path.join(tempDir, file);
        
        if (file === 'dapp.conf') {
            fs.writeFileSync(dest, generateInboxDappConf());
            console.log(`   ✓ Generated: ${file}`);
        } else if (file === 'config.js') {
            fs.writeFileSync(dest, generateInboxConfig(vendorConfig));
            console.log(`   ✓ Generated: ${file} (with vendor address)`);
        } else {
            copyFileSync(src, dest);
            console.log(`   ✓ Copied: ${file}`);
        }
    }
    
    const zipPath = path.join(OUTPUT_DIR, `miShopInbox.mds.zip`);
    
    return new Promise((resolve, reject) => {
        const output = fs.createWriteStream(zipPath);
        const archive = archiver('zip', { zlib: { level: 9 } });
        
        output.on('close', () => {
            console.log(`\n✅ Inbox MiniDapp created!`);
            console.log(`📁 Output: ${zipPath}`);
            console.log(`📊 Size: ${(archive.pointer() / 1024).toFixed(2)} KB\n`);
            
            fs.rmSync(tempDir, { recursive: true, force: true });
            resolve(zipPath);
        });
        
        archive.on('error', (err) => {
            reject(err);
        });
        
        archive.pipe(output);
        archive.directory(tempDir, false);
        archive.finalize();
    });
}

function validateInputs(options) {
    const errors = [];
    
    if (!options.name) errors.push('Product name is required');
    
    const mode = options.mode || 'weight';
    
    if (mode === 'units') {
        if (!options.price && options.price !== 0) errors.push('Price per unit is required');
        if (options.price && isNaN(parseFloat(options.price))) errors.push('Price must be a number');
        if (options.price && parseFloat(options.price) <= 0) errors.push('Price must be greater than 0');
        if (!options.units && options.units !== 0) errors.push('Max units is required for units mode');
        if (options.units && (isNaN(parseInt(options.units)) || parseInt(options.units) < 1)) errors.push('Max units must be at least 1');
    } else {
        if (!options.price && options.price !== 0) errors.push('Price per gram is required');
        if (options.price && isNaN(parseFloat(options.price))) errors.push('Price must be a number');
        if (options.price && parseFloat(options.price) <= 0) errors.push('Price must be greater than 0');
        if (!options.weight && options.weight !== 0) errors.push('Weight is required');
        if (options.weight && isNaN(parseFloat(options.weight))) errors.push('Weight must be a number');
        if (options.weight && parseFloat(options.weight) <= 0) errors.push('Weight must be greater than 0');
    }
    
    return errors;
}

async function main() {
    const program = new Command();
    
    program
        .name('generator')
        .description('Generate miShop MiniDapps for the Minima blockchain')
        .version('1.0.0')
        .option('-n, --name <name>', 'Product name')
        .option('-m, --mode <mode>', 'Sales mode: weight or units', 'weight')
        .option('-p, --price <price>', 'Price (per gram for weight, per unit for units)')
        .option('-w, --weight <weight>', 'Total weight in grams (for weight mode)')
        .option('-u, --units <units>', 'Max units per "full" (for units mode)', parseInt)
        .option('-d, --desc <description>', 'Product description')
        .option('-i, --image <path>', 'Path to product image')
        .option('--inbox-only', 'Only generate the inbox MiniDapp (skip shop)');
    
    program.parse(process.argv);
    const options = program.opts();
    
    const vendorConfig = loadConfig();
    if (!vendorConfig) {
        console.error(`
╔═══════════════════════════════════════════════════════════╗
║                    ⚠️  Setup Required                      ║
╠═══════════════════════════════════════════════════════════╣
║  You need to configure your vendor address first.          ║
║                                                               ║
║  Run: node setup.js <your-minima-address>                   ║
╚═══════════════════════════════════════════════════════════╝
`);
        process.exit(1);
    }
    
    if (options.inboxOnly) {
        await buildInboxMiniDapp();
        return;
    }
    
    const errors = validateInputs(options);
    if (errors.length > 0 || Object.keys(options).length === 0) {
        if (errors.length > 0) {
            console.error('\n❌ Validation errors:');
            errors.forEach(e => console.error(`   - ${e}`));
        }
        console.log(`
╔═══════════════════════════════════════════════════════════╗
║               🛒 miShop Generator 🛒                      ║
╠═══════════════════════════════════════════════════════════╣
║  Create Shop and Inbox MiniDapps for the Minima blockchain ║
╚═══════════════════════════════════════════════════════════╝

Usage:
  node generator.js [options]

Options:
  -n, --name <name>         Product name (required for shop)
  -m, --mode <mode>         Sales mode: weight or units (default: weight)
  -p, --price <price>       Price (per gram or per unit)
  -w, --weight <weight>      Total weight in grams (weight mode)
  -u, --units <units>        Max units per "full" (units mode)
  -d, --desc <description>   Product description
  -i, --image <path>         Path to product image
      --inbox-only           Generate ONLY the inbox MiniDapp
  -h, --help                 Show help

Modes:
  weight (default)  - Buy by weight (Full/Half/Quarter/Eighth)
  units              - Buy by quantity (user selects number)

Examples:
  Weight mode:  node generator.js -n "Organic Barley" -m weight -p 5 -w 1000 -d "Premium malting barley"
  Units mode:   node generator.js -n "Rolled Oats" -m units -p 25 -u 100 -d "Organic rolled oats"
  Inbox only:   node generator.js --inbox-only

First Time Setup:
  node setup.js <your-minima-address> <cmc-api-key> <chainmail-public-key>
`);
        process.exit(errors.length > 0 ? 1 : 0);
    }
    
    const mode = options.mode || 'weight';
    
    const product = {
        name: options.name,
        mode: mode,
        pricePerGram: mode === 'weight' ? parseFloat(options.price) : 0,
        pricePerUnit: mode === 'units' ? parseFloat(options.price) : 0,
        weight: mode === 'weight' ? parseFloat(options.weight) : 0,
        maxUnits: mode === 'units' ? parseInt(options.units) : 10,
        description: options.desc || 'Premium product'
    };
    
    const priceLabel = mode === 'units' ? 'per unit' : 'per gram';
    const weightLabel = mode === 'units' ? `Max units: ${product.maxUnits}` : `Weight: ${product.weight}g`;
    
    console.log(`
╔═══════════════════════════════════════════════════════════╗
║               🛒 miShop Generator 🛒                      ║
╚═══════════════════════════════════════════════════════════╝

📦 Product Details:
   Name:        ${product.name}
   Mode:        ${mode === 'units' ? 'Units (quantity)' : 'Weight (by gram)'}
   Price:       $${(product.pricePerUnit || product.pricePerGram).toFixed(2)}/${priceLabel.replace('per ', '')}
   ${weightLabel}
   Description: ${product.description}
`);
    
    await buildShopMiniDapp(product, options.image || './item.jpg');
    await buildInboxMiniDapp();
    
    console.log(`
╔═══════════════════════════════════════════════════════════╗
║                    ✅ Generation Complete!                  ║
╠═══════════════════════════════════════════════════════════╣
║  📤 Distribute to BUYERS:                                 ║
║     miniShop_${product.name.replace(/[^a-zA-Z0-9]/g, '_')}.mds.zip      ║
║                                                               ║
║  📬 KEEP FOR YOURSELF (Vendor):                           ║
║     miShopInbox.mds.zip                                    ║
║     Install on your node to receive orders!                 ║
╚═══════════════════════════════════════════════════════════╝
`);
}

main().catch(console.error);
