// Vendor Configuration - Generated by miShop Generator
// This inbox is paired with your miShop stores

const INBOX_CONFIG = {
    vendorAddress: "PLACEHOLDER",
    appName: "miShopInbox",
    version: "1.0.0"
};
