#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { Command } = require('commander');
const archiver = require('archiver');

const {
    loadConfig,
    deleteConfig,
    saveConfig,
    generateSalt,
    obfuscateAddress,
    obfuscateApiKey,
    validateAddress,
    validatePublicKey,
    maskString,
    getConfigPath,
    CONFIG_DIR
} = require('./setup');

const OUTPUT_DIR = path.join(process.cwd(), 'dist');
const TEMPLATE_DIR = path.join(__dirname, '..', 'template');
const SHOP_TEMPLATE_DIR = path.join(TEMPLATE_DIR, 'shop');
const INBOX_TEMPLATE_DIR = path.join(TEMPLATE_DIR, 'inbox');

function ensureDir(dir) {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

function copyFileSync(src, dest) {
    if (fs.existsSync(src)) {
        fs.copyFileSync(src, dest);
        return true;
    }
    return false;
}

function safeName(name) {
    return name.replace(/[^a-zA-Z0-9]/g, '_');
}

function calculateSizes(totalWeight) {
    return [
        { id: 'full',    name: 'Full',    weight: totalWeight,       multiplier: 1.0,   percentage: 100 },
        { id: 'half',    name: 'Half',    weight: totalWeight / 2,   multiplier: 0.5,   percentage: 50 },
        { id: 'quarter', name: 'Quarter', weight: totalWeight / 4,   multiplier: 0.25,  percentage: 25 },
        { id: 'eighth',  name: 'Eighth',  weight: totalWeight / 8,  multiplier: 0.125, percentage: 12.5 }
    ];
}

function generateProductsJs(products, slippageRate) {
    // Accept either a single product object (legacy) or an array
    const productArray = Array.isArray(products) ? products : [products];
    const slippage = typeof slippageRate === 'number' ? slippageRate : 10;

    const productsJson = productArray.map((product, idx) => {
        const sizes = calculateSizes(
            product.mode === 'units' ? product.maxUnits : product.weight
        );
        const imageFile = productArray.length === 1 ? 'item.jpg' : `item_${idx}.jpg`;
        return `    {
        name: ${JSON.stringify(product.name)},
        description: ${JSON.stringify(product.description)},
        mode: ${JSON.stringify(product.mode || 'weight')},
        pricePerUnit: ${product.pricePerUnit || 0},
        pricePerGram: ${product.pricePerGram || 0},
        totalWeight: ${product.weight || 0},
        maxUnits: ${product.maxUnits || 10},
        image: ${JSON.stringify(imageFile)},
        sizes: ${JSON.stringify(sizes, null, 8).replace(/\n/g, '\n        ')},
        rebroadcastDelayHours: ${product.rebroadcastDelayHours || 2},
        rebroadcastMaxIntervalHours: ${product.rebroadcastMaxIntervalHours || 24},
        firstRebroadcastDelayHours: ${product.firstRebroadcastDelayHours || 2},
        created: ${JSON.stringify(new Date().toISOString())}
    }`;
    }).join(',\n');

    return `// Product Configuration - Generated by miniMerch CLI
// DO NOT EDIT - Regenerate using: mini-merch generate or mini-merch generate-multi

// Slippage buffer applied to Minima payments at checkout (vendor-defined %)
const SLIPPAGE_RATE = ${slippage};

const PRODUCTS = [
${productsJson}
];

// Backward-compat alias — single-product shops use this directly
// Declared as let so the carousel can reassign it when navigating products
let PRODUCT = PRODUCTS[0];

function calculateSizesForWeight(totalWeight) {
    return [
        { id: 'full',    name: 'Full',    weight: totalWeight,       multiplier: 1.0,   percentage: 100 },
        { id: 'half',    name: 'Half',    weight: totalWeight / 2,   multiplier: 0.5,   percentage: 50 },
        { id: 'quarter', name: 'Quarter', weight: totalWeight / 4,   multiplier: 0.25,  percentage: 25 },
        { id: 'eighth',  name: 'Eighth',  weight: totalWeight / 8,   multiplier: 0.125, percentage: 12.5 }
    ];
}

function getPriceForSize(sizeId, product) {
    const p = product || PRODUCT;
    const size = p.sizes.find(s => s.id === sizeId);
    if (!size) return 0;
    if (p.mode === 'units') return p.pricePerUnit * size.weight;
    return p.pricePerGram * size.weight;
}
`;
}

function generateConfigJs(config) {
    return `// Vendor Configuration - Generated by miniMerch CLI
// Address is obfuscated to prevent tampering

const VENDOR_CONFIG = {
    obfuscatedAddress: "${config.obfuscated}",
    salt: "${config.salt}",
    obfuscatedApiKey: "${config.obfuscatedApiKey || ''}",
    vendorPublicKey: "${config.vendorPublicKey || ''}",
    inboxPublicKey: "${config.inboxPublicKey || ''}",
    appName: "miniMerch",
    version: "1.0.0"
};
`;
}

function generateShopDappConf(product) {
    return `{
    "name": "miniMerch",
    "version": "1.0.0",
    "headline": "${product.name}",
    "description": "${product.description}",
    "icon": "./icon.svg",
    "category": "Shopping"
}`;
}

function generateInboxDappConf() {
    return `{
    "name": "miniMerchInbox",
    "version": "1.0.0",
    "headline": "miniMerch Order Inbox",
    "description": "Receive and manage orders from your miniMerch shops",
    "icon": "./icon.svg",
    "category": "Shopping"
}`;
}

function generateInboxConfig(config) {
    return `// Vendor Configuration - Generated by miniMerch CLI
// This inbox is paired with your miniMerch shops

const INBOX_CONFIG = {
    obfuscatedVendorAddress: "${config.obfuscated}",
    appName: "miniMerchInbox",
    version: "1.0.0"
};
`;
}

// products: single product object (legacy) or array of up to 8
// imagePaths: single path string (legacy) or array of paths matching products
async function buildShopMiniDapp(products, imagePaths, slippageRate) {
    const productArray = Array.isArray(products) ? products : [products];
    const imagePathArray = Array.isArray(imagePaths) ? imagePaths : [imagePaths];
    const slippage = typeof slippageRate === 'number' ? slippageRate : 10;
    const isMulti = productArray.length > 1;

    ensureDir(OUTPUT_DIR);
    const tempDir = path.join(OUTPUT_DIR, 'temp_shop_' + Date.now());
    ensureDir(tempDir);

    console.log(`\n📦 Building miniMerch Shop MiniDapp (${productArray.length} product${productArray.length > 1 ? 's' : ''})...\n`);

    const vendorConfig = loadConfig();
    if (!vendorConfig) {
        console.error('\n❌ Error: Vendor config not found. Run "mini-merch setup" first.\n');
        process.exit(1);
    }

    const files = fs.readdirSync(SHOP_TEMPLATE_DIR);
    for (const file of files) {
        const src = path.join(SHOP_TEMPLATE_DIR, file);
        const dest = path.join(tempDir, file);

        if (file === 'products.js') {
            fs.writeFileSync(dest, generateProductsJs(productArray, slippage));
            console.log(`   ✓ Generated: ${file} (slippage: ${slippage}%)`);
        } else if (file === 'config.js') {
            fs.writeFileSync(dest, generateConfigJs(vendorConfig));
            console.log(`   ✓ Generated: ${file} (with obfuscated address)`);
        } else if (file === 'app.js') {
            let content = fs.readFileSync(src, 'utf8');
            content = content.replace("const OBFUSCATED_CMC_KEY = '';", `const OBFUSCATED_CMC_KEY = '${vendorConfig.obfuscatedApiKey}';`);
            content = content.replace("const CMC_KEY_SALT = '';", `const CMC_KEY_SALT = '${vendorConfig.salt}';`);
            fs.writeFileSync(dest, content);
            console.log(`   ✓ Generated: ${file} (with obfuscated API key)`);
        } else if (file === 'dapp.conf') {
            fs.writeFileSync(dest, generateShopDappConf(productArray[0]));
            console.log(`   ✓ Generated: ${file}`);
        } else if (file === 'item.jpg' && isMulti) {
            // Skip default image for multi-product — images are item_0.jpg, item_1.jpg etc.
        } else {
            copyFileSync(src, dest);
            console.log(`   ✓ Copied: ${file}`);
        }
    }

    // Copy product images
    if (isMulti) {
        productArray.forEach((product, idx) => {
            const imgPath = imagePathArray[idx];
            if (imgPath && fs.existsSync(imgPath)) {
                const ext = path.extname(imgPath);
                copyFileSync(imgPath, path.join(tempDir, `item_${idx}${ext}`));
                console.log(`   ✓ Copied: item_${idx}${ext} (${product.name})`);
            } else {
                // Fall back to default item.jpg, renamed to item_N.jpg
                const defaultImg = path.join(SHOP_TEMPLATE_DIR, 'item.jpg');
                if (fs.existsSync(defaultImg)) {
                    copyFileSync(defaultImg, path.join(tempDir, `item_${idx}.jpg`));
                    console.log(`   ✓ Copied: item_${idx}.jpg (default, ${product.name})`);
                }
                if (imgPath) console.warn(`   ⚠️  Warning: Image not found at ${imgPath}`);
            }
        });
    } else {
        // Single product — legacy behaviour
        const imagePath = imagePathArray[0];
        if (imagePath) {
            if (fs.existsSync(imagePath)) {
                const ext = path.extname(imagePath);
                const destImage = path.join(tempDir, 'item' + ext);
                copyFileSync(imagePath, destImage);
                if (ext !== '.jpg') {
                    let content = fs.readFileSync(path.join(tempDir, 'products.js'), 'utf8');
                    content = content.replace('item.jpg', 'item' + ext);
                    fs.writeFileSync(path.join(tempDir, 'products.js'), content);
                }
                console.log(`   ✓ Copied: item${ext}`);
            } else {
                console.warn(`   ⚠️  Warning: Image not found at ${imagePath}`);
            }
        }
    }

    const zipName = isMulti
        ? `miniMerch_Shop.mds.zip`
        : `miniMerch_${safeName(productArray[0].name)}.mds.zip`;
    const zipPath = path.join(OUTPUT_DIR, zipName);

    return new Promise((resolve, reject) => {
        const output = fs.createWriteStream(zipPath);
        const archive = archiver('zip', { zlib: { level: 9 } });
        output.on('close', () => {
            console.log(`\n✅ Shop MiniDapp created!`);
            console.log(`📁 Output: ${zipPath}`);
            console.log(`📊 Size: ${(archive.pointer() / 1024).toFixed(2)} KB\n`);
            fs.rmSync(tempDir, { recursive: true, force: true });
            resolve(zipPath);
        });
        archive.on('error', reject);
        archive.pipe(output);
        archive.directory(tempDir, false);
        archive.finalize();
    });
}

async function buildInboxMiniDapp() {
    ensureDir(OUTPUT_DIR);
    const tempDir = path.join(OUTPUT_DIR, 'temp_inbox_' + Date.now());
    ensureDir(tempDir);

    console.log('\n📬 Building miniMerchInbox MiniDapp...\n');

    const vendorConfig = loadConfig();
    if (!vendorConfig) {
        console.error('\n❌ Error: Vendor config not found. Run "mini-merch setup" first.\n');
        process.exit(1);
    }

    const files = fs.readdirSync(INBOX_TEMPLATE_DIR);
    for (const file of files) {
        const src = path.join(INBOX_TEMPLATE_DIR, file);
        const dest = path.join(tempDir, file);

        if (file === 'dapp.conf') {
            fs.writeFileSync(dest, generateInboxDappConf());
            console.log(`   ✓ Generated: ${file}`);
        } else if (file === 'config.js') {
            fs.writeFileSync(dest, generateInboxConfig(vendorConfig));
            console.log(`   ✓ Generated: ${file} (with vendor address)`);
        } else {
            copyFileSync(src, dest);
            console.log(`   ✓ Copied: ${file}`);
        }
    }

    const zipPath = path.join(OUTPUT_DIR, 'miniMerchInbox.mds.zip');

    return new Promise((resolve, reject) => {
        const output = fs.createWriteStream(zipPath);
        const archive = archiver('zip', { zlib: { level: 9 } });
        output.on('close', () => {
            console.log(`\n✅ Inbox MiniDapp created!`);
            console.log(`📁 Output: ${zipPath}`);
            console.log(`📊 Size: ${(archive.pointer() / 1024).toFixed(2)} KB\n`);
            fs.rmSync(tempDir, { recursive: true, force: true });
            resolve(zipPath);
        });
        archive.on('error', reject);
        archive.pipe(output);
        archive.directory(tempDir, false);
        archive.finalize();
    });
}

function validateInputs(options) {
    const errors = [];
    if (!options.name) errors.push('Product name is required (use -n or --name)');
    const mode = options.mode || 'weight';
    if (mode === 'units') {
        if (!options.price && options.price !== 0) errors.push('Price per unit is required (use -p or --price)');
        if (options.price && isNaN(parseFloat(options.price))) errors.push('Price must be a number');
        if (options.price && parseFloat(options.price) <= 0) errors.push('Price must be greater than 0');
        if (!options.units && options.units !== 0) errors.push('Max units is required for units mode (use -u or --units)');
        if (options.units && (isNaN(parseInt(options.units)) || parseInt(options.units) < 1)) {
            errors.push('Max units must be at least 1');
        }
    } else {
        if (!options.price && options.price !== 0) errors.push('Price per gram is required (use -p or --price)');
        if (options.price && isNaN(parseFloat(options.price))) errors.push('Price must be a number');
        if (options.price && parseFloat(options.price) <= 0) errors.push('Price must be greater than 0');
        if (!options.weight && options.weight !== 0) errors.push('Weight is required for weight mode (use -w or --weight)');
        if (options.weight && isNaN(parseFloat(options.weight))) errors.push('Weight must be a number');
        if (options.weight && parseFloat(options.weight) <= 0) errors.push('Weight must be greater than 0');
    }
    return errors;
}

function runSetup() {
    const address = process.argv[3];
    const apiKey = process.argv[4];
    const vendorPublicKey = process.argv[5];
    const inboxPublicKey = process.argv[6];

    if (!address || !apiKey || !vendorPublicKey) {
        console.log(`
╔═══════════════════════════════════════════════════════════╗
║           miniMerch CLI - Setup                     ║
╠═══════════════════════════════════════════════════════════╣
║  This saves your vendor configuration to:              ║
║  ${CONFIG_DIR.padEnd(49)}║
║                                                          ║
║  Values are obfuscated to prevent tampering.             ║
╚═══════════════════════════════════════════════════════════╝

Usage:
  mini-merch setup <minima-address> <cmc-api-key> <vendor-public-key> [inbox-public-key]

Arguments:
  minima-address        Your Minima receiving address (starts with 0x)
  cmc-api-key           CoinMarketCap API key for live prices
  vendor-public-key      Your public key for encrypted messages (starts with Mx)
  inbox-public-key       (Optional) Separate inbox public key

Example:
  mini-merch setup 0x465CA86A9B5756F45DEB667A69B3DBEC1B82B211814B294ED32693603F28AD37 c1d37f5f89564ca5868d21e2303c281b MxG18HGG6FJ038614Y8CW46US6G20810K0070CD00Z83282G60G19TUFFWSB6EEF0619DH9A069ECNU1TNEFRBHKTE8DU5T9740QUW30BH9F45YSZUM5SSVUHU36WFGSWDZS6CZYGB4AJG83VQPUF42R6S11Z9R70MUQCJRG202YQK7Z4FS904R7V4W8ZBHK7D5STVHK1GYSV54HJSBRE1MUTHNHCCGV9BUWE2FZBEND91D421Z6V2Z7BRGMTECVC10608006P3DB2S

To get your vendor public key:
  1. Generate and open miniMerchInbox.mds.zip in your Minima node
  2. Your public key will be displayed in the app
  3. Copy it and use as the 3rd argument above
`);
        process.exit(1);
    }

    const addressValidation = validateAddress(address);
    if (!addressValidation.valid) {
        console.error(`❌ ${addressValidation.error}`);
        console.error('\n   Your Minima address looks like: 0x465CA86A9B5756F45DEB667A69B3DBEC1B82B211814B294ED32693603F28AD37');
        console.error('   Find it in your Minima node or MiniMask wallet.');
        process.exit(1);
    }

    const pubkeyValidation = validatePublicKey(vendorPublicKey, 'vendor public key');
    if (!pubkeyValidation.valid) {
        console.error(`❌ ${pubkeyValidation.error}`);
        console.error('\n   Your public key looks like: MxG18HGG6FJ038614Y8CW46US6G20810K0070CD00Z83282G60G...');
        console.error('   Get it from your miniMerchInbox MiniDapp.');
        process.exit(1);
    }

    if (inboxPublicKey) {
        const inboxValidation = validatePublicKey(inboxPublicKey, 'inbox public key');
        if (!inboxValidation.valid) {
            console.error(`❌ ${inboxValidation.error}`);
            process.exit(1);
        }
    }

    const existing = loadConfig();
    if (existing) {
        console.log(`⚠️  Config already exists at: ${getConfigPath()}`);
        console.log(`   Created: ${existing.created}`);
        console.log('\n   To overwrite, first run: mini-merch config --reset');
        process.exit(1);
    }

    const salt = generateSalt();
    const obfuscated = obfuscateAddress(address, salt);
    const obfuscatedKey = obfuscateApiKey(apiKey, salt);

    console.log(`
╔═══════════════════════════════════════════════════════════╗
║           miniMerch CLI - Setup                     ║
╚═══════════════════════════════════════════════════════════╝
🔐 Saving obfuscated config...
  Address:    ${maskString(address, 10, 8)}
  CMC Key:    ${maskString(apiKey, 4, 4)}
  Pub Key:    ${maskString(vendorPublicKey, 12, 8)}
${inboxPublicKey ? `  Inbox Key:  ${maskString(inboxPublicKey, 12, 8)}` : ''}
`);

    saveConfig(obfuscated, salt, obfuscatedKey, vendorPublicKey, inboxPublicKey);
    console.log(`
✅ Setup complete!

Config saved to: ${getConfigPath()}

Next, generate your shop:
  mini-merch generate -n "My Product" -m weight -p 5 -w 500 -d "Great product"
`);
}

function runConfig(args) {
    if (args.includes('--reset')) {
        const existing = loadConfig();
        if (!existing) {
            console.log('No config file found. Nothing to delete.');
            return;
        }
        deleteConfig();
        console.log(`✅ Config deleted from: ${getConfigPath()}`);
        return;
    }

    if (args.includes('--show')) {
        const existing = loadConfig();
        if (!existing) {
            console.log(`No config found. Run: mini-merch setup <address> <apikey> <pubkey>`);
            return;
        }
        console.log(`Config file: ${getConfigPath()}`);
        console.log(`Created: ${existing.created}`);
        console.log(`Address:    ${maskString(existing.obfuscated, 20, 20)} (obfuscated)`);
        console.log(`Pub Key:   ${maskString(existing.vendorPublicKey, 12, 8)}`);
        return;
    }

    console.log(`Config file: ${getConfigPath()}`);
    console.log(`Use --show to display current config, or --reset to delete it.`);
}

async function runGenerate(options) {
    const vendorConfig = loadConfig();
    if (!vendorConfig) {
        console.error(`
╔═══════════════════════════════════════════════════════════╗
║                    ⚠️  Setup Required                   ║
╠═══════════════════════════════════════════════════════════╣
║  No vendor config found. Run setup first:               ║
║                                                              ║
║    mini-merch setup <address> <apikey> <pubkey>          ║
╚═══════════════════════════════════════════════════════════╝
`);
        process.exit(1);
    }

    if (options.inboxOnly) {
        await buildInboxMiniDapp();
        return;
    }

    const errors = validateInputs(options);
    if (errors.length > 0) {
        console.error('\n❌ Validation errors:');
        errors.forEach(e => console.error(`   - ${e}`));
        console.log('\nRun "mini-merch generate --help" for usage information.');
        process.exit(1);
    }

    const mode = options.mode || 'weight';
    const product = {
        name: options.name,
        mode,
        pricePerGram: mode === 'weight' ? parseFloat(options.price) : 0,
        pricePerUnit: mode === 'units' ? parseFloat(options.price) : 0,
        weight: mode === 'weight' ? parseFloat(options.weight) : 0,
        maxUnits: mode === 'units' ? parseInt(options.units) : 10,
        description: options.desc || 'Premium product',
        firstRebroadcastDelayHours: options.rebroadcastDelay || 2,
        rebroadcastMaxIntervalHours: options.maxRebroadcast || 24
    };

    const priceLabel = mode === 'units' ? 'per unit' : 'per gram';
    const priceVal = product.pricePerUnit || product.pricePerGram;
    const sizeLabel = mode === 'units' ? `Max units: ${product.maxUnits}` : `Weight: ${product.weight}g`;

    console.log(`
╔═══════════════════════════════════════════════════════════╗
║               🛒 miniMerch Generator 🛒                  ║
╚═══════════════════════════════════════════════════════════╝
📦 Product Details:
   Name:        ${product.name}
   Mode:        ${mode === 'units' ? 'Units (quantity)' : 'Weight (by gram)'}
   Price:       $${priceVal.toFixed(2)}/${priceLabel.replace('per ', '')}
   ${sizeLabel}
   Description: ${product.description}
`);

    await buildShopMiniDapp([product], [options.image || path.join(__dirname, '..', 'item.jpg')], options.slippage || 10);
    await buildInboxMiniDapp();

    console.log(`
╔═══════════════════════════════════════════════════════════╗
║               ✅ Generation Complete!                      ║
╠═══════════════════════════════════════════════════════════╣
║  📤 Distribute to BUYERS:                                  ║
║     ./dist/miniMerch_${safeName(product.name)}.mds.zip${' '.repeat(Math.max(0, 12 - safeName(product.name).length))}║
║                                                               ║
║  📬 KEEP FOR YOURSELF (Vendor):                            ║
║     ./dist/miniMerchInbox.mds.zip                            ║
║     Install on your node to receive orders!                  ║
╚═══════════════════════════════════════════════════════════╝
`);
}

// ─── Interactive Multi-Product Wizard ────────────────────────────────────────

function ask(rl, question) {
    return new Promise(resolve => rl.question(question, resolve));
}

async function promptProduct(rl, idx) {
    console.log(`\n── Product ${idx + 1} ──────────────────────────────────────`);

    const name = (await ask(rl, '  Name: ')).trim();
    if (!name) return null; // empty name = done entering products

    const modeRaw = (await ask(rl, '  Mode [weight/units] (default: weight): ')).trim().toLowerCase();
    const mode = modeRaw === 'units' ? 'units' : 'weight';

    const priceRaw = (await ask(rl, `  Price per ${mode === 'units' ? 'unit' : 'gram'} (USD): `)).trim();
    const price = parseFloat(priceRaw);
    if (isNaN(price) || price <= 0) {
        console.error('  ❌ Invalid price. Skipping this product.');
        return null;
    }

    let weight = 0, maxUnits = 10;
    if (mode === 'weight') {
        const wRaw = (await ask(rl, '  Total batch weight in grams: ')).trim();
        weight = parseFloat(wRaw);
        if (isNaN(weight) || weight <= 0) {
            console.error('  ❌ Invalid weight. Skipping this product.');
            return null;
        }
    } else {
        const uRaw = (await ask(rl, '  Max units available: ')).trim();
        maxUnits = parseInt(uRaw);
        if (isNaN(maxUnits) || maxUnits < 1) {
            console.error('  ❌ Invalid units. Skipping this product.');
            return null;
        }
    }

    const desc = (await ask(rl, '  Description (optional): ')).trim() || 'Premium product';
    const image = (await ask(rl, '  Image path (optional, press Enter to skip): ')).trim() || null;

    return {
        name,
        mode,
        pricePerGram: mode === 'weight' ? price : 0,
        pricePerUnit: mode === 'units' ? price : 0,
        weight: mode === 'weight' ? weight : 0,
        maxUnits: mode === 'units' ? maxUnits : 10,
        description: desc,
        firstRebroadcastDelayHours: 2,
        rebroadcastMaxIntervalHours: 24,
        image
    };
}

async function runGenerateMulti() {
    const vendorConfig = loadConfig();
    if (!vendorConfig) {
        console.error(`
╔═══════════════════════════════════════════════════════════╗
║                    ⚠️  Setup Required                   ║
╠═══════════════════════════════════════════════════════════╣
║  No vendor config found. Run setup first:               ║
║                                                              ║
║    mini-merch setup <address> <apikey> <pubkey>          ║
╚═══════════════════════════════════════════════════════════╝
`);
        process.exit(1);
    }

    console.log(`
╔═══════════════════════════════════════════════════════════╗
║          🛒 miniMerch Multi-Product Wizard 🛒             ║
╠═══════════════════════════════════════════════════════════╣
║  Add up to 8 products. Leave Name blank when done.        ║
╚═══════════════════════════════════════════════════════════╝
`);

    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

    const products = [];
    const imagePaths = [];

    for (let i = 0; i < 8; i++) {
        const product = await promptProduct(rl, i);
        if (!product) break;
        imagePaths.push(product.image || path.join(__dirname, '..', 'item.jpg'));
        delete product.image;
        products.push(product);
        console.log(`  ✓ Added: ${product.name}`);
        if (i < 7) {
            const more = (await ask(rl, '\n  Add another product? [Y/n]: ')).trim().toLowerCase();
            if (more === 'n') break;
        }
    }

    if (products.length === 0) {
        rl.close();
        console.error('\n❌ No products entered. Aborting.\n');
        process.exit(1);
    }

    const slippageRaw = (await ask(rl, '\n  Slippage % for Minima payments (default 10, press Enter to keep): ')).trim();
    const slippage = slippageRaw ? parseFloat(slippageRaw) : 10;

    rl.close();

    console.log(`\n📦 Generating shop with ${products.length} product${products.length > 1 ? 's' : ''}, ${slippage}% slippage...\n`);
    products.forEach((p, i) => console.log(`   ${i + 1}. ${p.name}`));

    await buildShopMiniDapp(products, imagePaths, slippage);
    await buildInboxMiniDapp();

    console.log(`
╔═══════════════════════════════════════════════════════════╗
║               ✅ Generation Complete!                      ║
╠═══════════════════════════════════════════════════════════╣
║  📤 Distribute to BUYERS:                                  ║
║     ./dist/miniMerch_Shop.mds.zip                          ║
║                                                            ║
║  📬 KEEP FOR YOURSELF (Vendor):                            ║
║     ./dist/miniMerchInbox.mds.zip                          ║
║     Install on your node to receive orders!                ║
╚═══════════════════════════════════════════════════════════╝
`);
}

// ─────────────────────────────────────────────────────────────────────────────

async function main() {
    const subcommand = process.argv[2];

    if (subcommand === 'studio') {
        require('./studio').start();
        return;
    }

    if (subcommand === 'setup') {
        runSetup();
        return;
    }

    if (subcommand === 'config') {
        runConfig(process.argv);
        return;
    }

    if (subcommand === 'generate-multi') {
        await runGenerateMulti();
        return;
    }

    if (subcommand === 'generate') {
        const program = new Command();
        program
            .name('mini-merch generate')
            .description('Generate miniMerch MiniDapps')
            .option('-n, --name <name>', 'Product name')
            .option('-m, --mode <mode>', 'Sales mode: weight or units', 'weight')
            .option('-p, --price <price>', 'Price (per gram or per unit)')
            .option('-w, --weight <weight>', 'Total weight in grams (weight mode)')
            .option('-u, --units <units>', 'Max units per "full" (units mode)', parseInt)
            .option('-d, --desc <description>', 'Product description')
            .option('-i, --image <path>', 'Path to product image')
            .option('--inbox-only', 'Generate only the inbox MiniDapp')
            .option('--rebroadcast-delay <hours>', 'Hours before first rebroadcast attempt', parseInt, 2)
            .option('--max-rebroadcast <hours>', 'Max hours between rebroadcast attempts', parseInt, 24)
            .option('--slippage <percent>', 'Slippage % added to Minima payments at checkout (default 10)', parseFloat, 10);
        program.parse(process.argv);
        await runGenerate(program.opts());
        return;
    }

    const program = new Command();
    program
        .name('mini-merch')
        .description('Generate miniMerch MiniDapps for the Minima blockchain')
        .version('0.1.0');

    program
        .command('setup <address> <apikey> <pubkey> [inboxpubkey]')
        .description('Save vendor configuration (one-time setup)')
        .action(() => runSetup());

    program
        .command('generate')
        .description('Generate shop and/or inbox MiniDapps')
        .option('-n, --name <name>', 'Product name')
        .option('-m, --mode <mode>', 'Sales mode: weight or units', 'weight')
        .option('-p, --price <price>', 'Price (per gram or per unit)')
        .option('-w, --weight <weight>', 'Total weight in grams (weight mode)')
        .option('-u, --units <units>', 'Max units per "full" (units mode)', parseInt)
        .option('-d, --desc <description>', 'Product description')
        .option('-i, --image <path>', 'Path to product image')
        .option('--inbox-only', 'Generate only the inbox MiniDapp')
        .option('--rebroadcast-delay <hours>', 'Hours before first rebroadcast attempt', parseInt, 2)
        .option('--max-rebroadcast <hours>', 'Max hours between rebroadcast attempts', parseInt, 24)
        .option('--slippage <percent>', 'Slippage % added to Minima payments at checkout (default 10)', parseFloat, 10)
        .action(async (opts) => await runGenerate(opts));

    program
        .command('generate-multi')
        .description('Interactively build a shop with up to 8 products (carousel)')
        .action(async () => await runGenerateMulti());

    program
        .command('studio')
        .description('Open the miniMerch Studio web UI to build shops visually')
        .action(() => require('./studio').start());

    program
        .command('config')
        .description('Manage stored configuration')
        .option('--show', 'Display current config')
        .option('--reset', 'Delete stored config')
        .action((opts) => {
            const args = process.argv.slice(3);
            if (opts.reset) args.push('--reset');
            if (opts.show) args.push('--show');
            runConfig(args);
        });

    program.parse(process.argv);
}

main().catch(console.error);
