'use strict';

// studio-builder.js
// Handles the actual MiniDapp zip generation for the Studio web UI.
// Mirrors buildShopMiniDapp() + buildInboxMiniDapp() from index.js
// but is callable as a module without side effects.

const fs       = require('fs');
const path     = require('path');
const os       = require('os');
const archiver = require('archiver');

// When running as a pkg binary, assets live in the virtual snapshot at __dirname.
// Output files must go to the real filesystem.
const IS_PKG = !!process.pkg;

// Template assets are bundled inside the snapshot — always use __dirname
const SHOP_TEMPLATE_DIR  = path.join(__dirname, '..', 'template', 'shop');
const INBOX_TEMPLATE_DIR = path.join(__dirname, '..', 'template', 'inbox');
// Default image — also bundled
const DEFAULT_ITEM_JPG   = path.join(__dirname, '..', 'template', 'shop', 'icon.png');
// Output dir passed in by caller (already resolved to real fs by studio.js)

function ensureDir(d) { if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true }); }
function copyFile(s, d) { if (fs.existsSync(s)) fs.copyFileSync(s, d); }
function safeName(n)  { return n.replace(/[^a-zA-Z0-9]/g, '_'); }

function zipDir(tmpDir, outPath) {
    return new Promise((resolve, reject) => {
        const output  = fs.createWriteStream(outPath);
        const archive = archiver('zip', { zlib: { level: 9 } });
        output.on('close', () => resolve(archive.pointer()));
        archive.on('error', reject);
        archive.pipe(output);
        archive.directory(tmpDir, false);
        archive.finalize();
    });
}

function calculateSizes(total) {
    return [
        { id: 'full',    name: 'Full',    weight: total,       multiplier: 1.0,   percentage: 100   },
        { id: 'half',    name: 'Half',    weight: total / 2,   multiplier: 0.5,   percentage: 50    },
        { id: 'quarter', name: 'Quarter', weight: total / 4,   multiplier: 0.25,  percentage: 25    },
        { id: 'eighth',  name: 'Eighth',  weight: total / 8,   multiplier: 0.125, percentage: 12.5  },
    ];
}

function generateProductsJs(products, slippage) {
    const slip = typeof slippage === 'number' ? slippage : 10;
    const productsJson = products.map((p, i) => {
        const sizes     = calculateSizes(p.mode === 'units' ? p.maxUnits : p.weight);
        const imageFile = products.length === 1 ? 'item.jpg' : `item_${i}.jpg`;
        return `    {
        name: ${JSON.stringify(p.name)},
        description: ${JSON.stringify(p.description || 'Premium product')},
        mode: ${JSON.stringify(p.mode)},
        pricePerUnit: ${p.pricePerUnit || 0},
        pricePerGram: ${p.pricePerGram || 0},
        totalWeight: ${p.weight || 0},
        maxUnits: ${p.maxUnits || 10},
        image: ${JSON.stringify(imageFile)},
        sizes: ${JSON.stringify(sizes, null, 8).replace(/\n/g, '\n        ')},
        rebroadcastDelayHours: ${p.firstRebroadcastDelayHours || 2},
        rebroadcastMaxIntervalHours: ${p.rebroadcastMaxIntervalHours || 24},
        firstRebroadcastDelayHours: ${p.firstRebroadcastDelayHours || 2},
        created: "${new Date().toISOString()}"
    }`;
    }).join(',\n');

    return `// Product Configuration - Generated by miniMerch Studio
// DO NOT EDIT - Regenerate using: mini-merch studio

// Slippage buffer applied to Minima payments at checkout (vendor-defined %)
const SLIPPAGE_RATE = ${slip};

const PRODUCTS = [
${productsJson}
];

// Backward-compat alias
let PRODUCT = PRODUCTS[0];

function calculateSizesForWeight(totalWeight) {
    return [
        { id: 'full',    name: 'Full',    weight: totalWeight,       multiplier: 1.0,   percentage: 100   },
        { id: 'half',    name: 'Half',    weight: totalWeight / 2,   multiplier: 0.5,   percentage: 50    },
        { id: 'quarter', name: 'Quarter', weight: totalWeight / 4,   multiplier: 0.25,  percentage: 25    },
        { id: 'eighth',  name: 'Eighth',  weight: totalWeight / 8,   multiplier: 0.125, percentage: 12.5  },
    ];
}

function getPriceForSize(sizeId, product) {
    const p    = product || PRODUCT;
    const size = p.sizes.find(s => s.id === sizeId);
    if (!size) return 0;
    return p.mode === 'units' ? p.pricePerUnit * size.weight : p.pricePerGram * size.weight;
}
`;
}

function generateConfigJs(cfg) {
    return `// Vendor Configuration - Generated by miniMerch Studio
const VENDOR_CONFIG = {
    obfuscatedAddress: "${cfg.obfuscated}",
    salt: "${cfg.salt}",
    obfuscatedApiKey: "${cfg.obfuscatedApiKey || ''}",
    vendorPublicKey: "${cfg.vendorPublicKey || ''}",
    inboxPublicKey: "${cfg.inboxPublicKey || ''}",
    appName: "miniMerch",
    version: "1.1.0"
};
`;
}

function generateShopDappConf(shopName, products) {
    const headline = shopName || (products[0] ? products[0].name : 'miniMerch Shop');
    let desc;
    if (products.length > 1) {
        const full = `${products.length} products — ${products.map(p => p.name).join(', ')}`;
        desc = full.length > 200 ? full.substring(0, 197) + '...' : full;
    } else {
        desc = products[0] ? products[0].description || products[0].name : 'miniMerch shop';
    }
    return JSON.stringify({
        name:        'miniMerch',
        version:     '1.0.0',
        headline:    headline,
        description: desc,
        icon:        './icon.svg',
        category:    'Shopping',
    }, null, 4);
}

function generateInboxDappConf() {
    return JSON.stringify({
        name:        'miniMerchInbox',
        version:     '1.0.0',
        headline:    'miniMerch Order Inbox',
        description: 'Receive and manage orders from your miniMerch shops',
        icon:        './icon.svg',
        category:    'Shopping',
    }, null, 4);
}

async function build(products, imagePaths, slippage, shopName, distDir) {
    const { loadConfig } = require('./setup');
    const cfg = loadConfig();
    if (!cfg) throw new Error('Vendor config not found. Run "mini-merch setup" first.');

    ensureDir(distDir);
    const isMulti = products.length > 1;

    // ── Shop ──────────────────────────────────────────────────────────────────
    const shopTmp = path.join(distDir, 'tmp_studio_shop_' + Date.now());
    ensureDir(shopTmp);

    for (const file of fs.readdirSync(SHOP_TEMPLATE_DIR)) {
        const src  = path.join(SHOP_TEMPLATE_DIR, file);
        const dest = path.join(shopTmp, file);

        if (file === 'products.js') {
            fs.writeFileSync(dest, generateProductsJs(products, slippage));
        } else if (file === 'config.js') {
            fs.writeFileSync(dest, generateConfigJs(cfg));
        } else if (file === 'app.js') {
            let c = fs.readFileSync(src, 'utf8');
            c = c.replace("const OBFUSCATED_CMC_KEY = '';", `const OBFUSCATED_CMC_KEY = '${cfg.obfuscatedApiKey || ''}';`);
            c = c.replace("const CMC_KEY_SALT = '';",       `const CMC_KEY_SALT = '${cfg.salt}';`);
            fs.writeFileSync(dest, c);
        } else if (file === 'dapp.conf') {
            fs.writeFileSync(dest, generateShopDappConf(shopName, products));
        } else if (file === 'item.jpg' && isMulti) {
            // skip default image for multi-product
        } else {
            copyFile(src, dest);
        }
    }

    // Copy product images
    if (isMulti) {
        products.forEach((_, i) => {
            const imgPath   = imagePaths[i];
            const ext       = imgPath ? path.extname(imgPath) : '.jpg';
            const destImage = path.join(shopTmp, `item_${i}${ext}`);
            if (imgPath && fs.existsSync(imgPath)) {
                fs.copyFileSync(imgPath, destImage);
            } else {
        const fallback = DEFAULT_ITEM_JPG;
            if (fs.existsSync(fallback)) fs.copyFileSync(fallback, destImage);
        }
    });
    } else {
        const imgPath   = imagePaths[0];
        const ext       = imgPath ? path.extname(imgPath) : '.jpg';
        const destImage = path.join(shopTmp, 'item' + ext);
        if (imgPath && fs.existsSync(imgPath)) {
            fs.copyFileSync(imgPath, destImage);
            if (ext !== '.jpg') {
                const pjs = fs.readFileSync(path.join(shopTmp, 'products.js'), 'utf8');
                fs.writeFileSync(path.join(shopTmp, 'products.js'), pjs.replace('item.jpg', 'item' + ext));
            }
        } else {
            if (fs.existsSync(DEFAULT_ITEM_JPG)) copyFile(DEFAULT_ITEM_JPG, path.join(shopTmp, 'item.jpg'));
        }
    }

    const shopFileName = isMulti
        ? `miniMerch_${safeName(shopName || 'Shop')}.mds.zip`
        : `miniMerch_${safeName(products[0].name)}.mds.zip`;
    const shopZipPath  = path.join(distDir, shopFileName);
    const shopSize     = await zipDir(shopTmp, shopZipPath);
    fs.rmSync(shopTmp, { recursive: true, force: true });

    // ── Inbox ─────────────────────────────────────────────────────────────────
    const inboxTmp = path.join(distDir, 'tmp_studio_inbox_' + Date.now());
    ensureDir(inboxTmp);

    for (const file of fs.readdirSync(INBOX_TEMPLATE_DIR)) {
        const src  = path.join(INBOX_TEMPLATE_DIR, file);
        const dest = path.join(inboxTmp, file);
        if (file === 'dapp.conf') {
            fs.writeFileSync(dest, generateInboxDappConf());
        } else if (file === 'config.js') {
            fs.writeFileSync(dest, `const INBOX_CONFIG = { obfuscatedVendorAddress: "${cfg.obfuscated}", appName: "miniMerchInbox", version: "1.0.0" };`);
        } else {
            copyFile(src, dest);
        }
    }

    const inboxZipPath = path.join(distDir, 'miniMerchInbox.mds.zip');
    const inboxSize    = await zipDir(inboxTmp, inboxZipPath);
    fs.rmSync(inboxTmp, { recursive: true, force: true });

    return {
        shopFile:  shopFileName,
        inboxFile: 'miniMerchInbox.mds.zip',
        shopSize,
        inboxSize,
    };
}

module.exports = { build };
